import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { unstable_noStore } from "next/cache";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  unstable_noStore();
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
